//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerNewCate:BaseEntityModel
    {
        private string _GroupName;
        public string Name { get; set; }
        public bool Active { get; set; }
        public int GroupId { get; set; }
        public virtual string GroupName { 
            get { return _GroupName; } 
            set { _GroupName = this.GetGroup(); value = _GroupName; } 
        }
        public virtual string GetGroup()
        {
            switch(this.GroupId)
            {
                case 1: return "Siêu thị";
                    
                case 2: return "Hành chính";
            }
            return "";
        }
    }
}
