//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Core.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class District:BaseEntityModel
    {
        public int StateProviceId { get; set; }
        public string Name { get; set; }
        public virtual  StateProvice StateProvice { get; set; }
    }
}
