//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job.Core.Domain
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    
    public partial class News :BaseEntityModel
    {
        [Required(ErrorMessage="Vui lòng nhập tiêu đề")]
        public string Title { get; set; }
        public string Image { get; set; }
      
        [AllowHtml]
        [Required(ErrorMessage="Vui lòng nhập mô tả")]
        public string FullDescription { get; set; }
        public string ShortDes { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CreateBy { get; set; }
        public int ViewCount { get; set; }
    }
}
